### ISSUE TITLE
URGENT: P1 - Weather Bot Failure - Immediate Attention Required

### ISSUE THREAD

**Issue by linusromland** [Markussim/will-it-rain-2#3]
The weather bot failed to send the scheduled update at 8 AM today. This issue needs to be addressed with the highest priority.

## Impact:
- No weather update received at 8 AM
- Potential disruption to dependent services and users

## Action Required:

- Investigate the cause of the failure
- Restore the bot's functionality immediately
- Ensure future scheduled updates are not affected

**Comment by linusromland** [comment]
@Markussim FYI.

**Comment by linusromland** [comment]
@Markussim do you have an update on this? This is very urgent.
Thanks!

**Comment by Markussim** [comment]
Resolved @linusromland

**Comment by linusromland** [comment]
@Markussim 
Thank you for promptly resolving the issue; your swift action is greatly appreciated. Could you please provide an update on what went wrong and outline the measures taken to prevent a recurrence? Additionally, I would appreciate a full incident report detailing the situation.

Thanks once again for your support!

**Comment by Markussim** [comment]
Sure, here is a post-mortem report.

This was a two part issue, with two unrelated issues

## Part 1: Permissions
### Issue
The first issue was the easiest to resolve. When testing locally I'm running on my own account with much more permissions than in prod. This caused the application to fail as it lacked permissions for the new DynamoDB integration for history. 
### Solution
This was resolved by updating the execution role with a new policy.

## Part 2: Role ID
### Issue
This was much more confusing and I am still not sure why it happened. It seems like Discord has changed the role ID of the main role that the bot tags.
### Solution
This was resolved by changing the secret in Secrets Manager.

**Comment by Markussim** [comment]
@linusromland I have provided an incident report

**Comment by linusromland** [comment]
@Markussim Thanks!
